version: '3.4'
x-common-variables: &common-variables
  CONFIG_SERVICE_PASSWORD: "abc123"
  NOTIFICATION_SERVICE_PASSWORD: "abc123"
  STATISTICS_SERVICE_PASSWORD: "abc123"
  ACCOUNT_SERVICE_PASSWORD: "abc123"
  MONGODB_PASSWORD: "abc123"
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672"
    environment: *common-variables
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  config:
    build: config
    container_name: config
    ports:
      - "8888"
    environment: *common-variables
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  registry:
    build: registry
    container_name: registry
    environment: *common-variables
    restart: always
    ports:
      - "8761"
    depends_on:
      config:
        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  gateway:
    build: gateway
    container_name: gateway
    environment: *common-variables
    restart: always
    ports:
      - "80:4000"
    depends_on:
      config:
        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  auth-service:
    build: auth-service
    container_name: auth-service
    ports:
      - "5000"
    environment: *common-variables
    restart: always
    depends_on:
      config:
        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  auth-mongodb:
    build: mongodb
    container_name: "auth-mongodb"
    ports:
      - "27017"
    environment: *common-variables
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  account-service:
    build: account-service
    container_name: account-service
    ports:
      - "6001"
    environment: *common-variables
    restart: always
    depends_on:
      config:
        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  account-mongodb:
    build: mongodb
    container_name: "account-mongodb"
    ports:
      - "27017"
    environment:
      <<: *common-variables
      INIT_DUMP: account-service-dump.js
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  statistics-service:
    build: statistics-service
    container_name: statistics-service
    ports:
      - "7000"
    environment: *common-variables
    restart: always
    depends_on:
      config:
        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  statistics-mongodb:
    build: mongodb
    container_name: "statistics-mongodb"
    ports:
      - "27017"
    environment: *common-variables
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  notification-service:
    build: notification-service
    container_name: notification-service
    ports:
      - "8000"
    environment: *common-variables
    restart: always
    depends_on:
      config:
        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  notification-mongodb:
    build: mongodb
    container_name: "notification-mongodb"
    ports:
      - "27017"
    environment: *common-variables
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  monitoring:
    build: monitoring
    environment: *common-variables
    restart: always
    ports:
      - "9000:8080"
    depends_on:
      config:
        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  turbine-stream-service:
    build: turbine-stream-service
    environment: *common-variables
    restart: always
    ports:
      - "8989:8989"
    depends_on:
      config:
        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "10"
